CREATE TABLE RECRUTADOR(
    ID_RECRUTADOR SERIAL PRIMARY KEY,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    NOME_EMPRESA VARCHAR(100) NOT NULL,
    URL_LOGO VARCHAR(500),
    NOME_COMPLETO VARCHAR(100) NOT NULL
);

CREATE TABLE SETOR(
    ID_SETOR SERIAL PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    ID_RECRUTADOR BIGINT NOT NULL,
    FOREIGN KEY (ID_RECRUTADOR) REFERENCES RECRUTADOR (ID_RECRUTADOR)
);


CREATE TABLE VAGA(
    ID_VAGA SERIAL PRIMARY KEY,
    TITULO_VAGA VARCHAR(100) NOT NULL,
    NIVEL VARCHAR(100) NOT NULL,
    EXP_MIN INT NOT NULL,
    DESCRICAO TEXT NOT NULL,
    ID_RECRUTADOR BIGINT NOT NULL,
    ID_SETOR BIGINT NOT NULL,
    FOREIGN KEY (ID_RECRUTADOR) REFERENCES RECRUTADOR (ID_RECRUTADOR),
    FOREIGN KEY (ID_SETOR) REFERENCES SETOR (ID_SETOR)
);

CREATE TABLE CANDIDATURA(
    ID_CANDIDATURA SERIAL PRIMARY KEY,
    NOME_C0MPLETO VARCHAR(150) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    TELEFONE VARCHAR(11) NOT NULL,
    EXP INT NOT NULL,
    ID_VAGA BIGINT NOT NULL,
    FOREIGN KEY (ID_VAGA) REFERENCES VAGA (ID_VAGA)
);


CREATE TABLE SKILL(
    ID_SKILL SERIAL PRIMARY KEY,
    DESCRICAO VARCHAR(50),
    NIVEL VARCHAR(100),
    ID_VAGA BIGINT,
    ID_CANDIDATURA BIGINT,
    FOREIGN KEY (ID_VAGA) REFERENCES VAGA (ID_VAGA),
    FOREIGN KEY (ID_CANDIDATURA) REFERENCES CANDIDATURA (ID_CANDIDATURA)
);




